version: '3.7'

services:
    backend:
        build: ../simple-api-student-main
        networks:
          ["my-network"]
        depends_on:
          ["database"]

    database:
        build: ../database
        networks:
          ["my-network"]

    httpd:
        build: ../http
        ports:
          ["8081:80"]
        networks:
          ["my-network"]
        depends_on:
          ["backend"]

networks:
    my-network:
